### PR TITLE
Default table name can be configured. Fix #2

### LINKED ISSUE #2: Table name should be configurable
The automatic creation of a table named "audit" prevents me from using this library in a project.

Is there something that prevents the table name from being configurable? Is there any chance this will be implemented? Do you accept pull-requests?

### PR DESCRIPTION
**Pull request by theborakompanioni**
Introduces a bunch of changes - most notably:
- use try-with-resources whenever possible
- removes Singleton pattern from class `AuditLogDaoImpl`
- add setter `setDefault_table_name` to `DatabaseAuditHandler`
- prevent NPE when shutting down `DatabaseAuditHandler`

I tried to be consistent with your coding style (underscores in variable names, etc.).
I'd change a few additional things - but want to wait on your feedback.

### CODE REVIEW

**Comment by janithb** [comment]
Reviewed.! Merging.

**Comment by janithb** [comment]
@theborakompanioni Thank you very much for the pull request. Will release this in next week after testing.

**Comment by theborakompanioni** [comment]
@janithb No problem. But there are still some issues that should be addressed (e.g. better handling of AuditLogDaoImpl objects - currently in a map withSoftReference). Would you mind introducing a third party library like [Guava](https://github.com/google/guava) (and a mocking library like [mockito](http://mockito.org/) for testing)? I know I could write my own `core.handler.Handler` implementation.. but I prefer to contribute as long as you are comfortable with it.

**Comment by janithb** [comment]
@theborakompanioni I really appreciate your contributions. I don't see any issue with Guava and mockito. Send pull request anytime if you have any improvements.

**Comment by janithb** [comment]
@theborakompanioni I really appreciate your contributions. I don't see any issue with Guava and mockito. Send pull request anytime if you have any improvements. 

We are maintaining milestone list with tasks for each release. I hope this will help you. Please refer below link.
https://docs.google.com/document/d/1UQhG3oVzS9216u5oT8B0dWs95YHzLFiaHQXrx0TbcVg/edit

I was planning to use asynchronous jdbc calls to prevent blocking of reactor event loop in audit4j core. I found [vertx](http://vertx.io/docs/vertx-jdbc-client/java/) to achieve this feature.

**Pull request merged**
